[build]
  publish = "build"  # This is the default output folder for Create React App
  command = "npm run build"  # This builds your app



[[redirects]]
  from = "/api/*"
  to = "https://capstone-rms.onrender.com/api/:splat"
  status = 200
  force = true